AllCops:
  Exclude:
    - "db/**"
    - bin/bundle
    - "**/vendor/**/*"
    - "**/*.gemspec"
    - "spec/**"
  NewCops: enable
  TargetRubyVersion: 3.2.2
  TargetRailsVersion: 7
  SuggestExtensions: false

require:
  - rubocop-rails

Rails:
  Enabled: true

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false
