name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Install dependencies
      run: make install-without-production

#    - name: Run tests & publish code coverage
#      # https://github.com/paambaati/codeclimate-action
#      uses: MartinNuc/codeclimate-action@1
#      with:
#        coverageCommand: make test-all-coverage
#        debug: false

    - name: Run linters
      run: make lint
